name: manga_viewer
description: A minimal manga viewer app that loads zip files
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # File picker for selecting zip files
  file_picker: ^6.1.1
  
  # Archive library for extracting zip files
  archive: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true