name: CI

on:
  push:
    branches: [ main, develop, 'feature/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Ubuntu job - Run tests for Electron/React app
  ubuntu-test:
    name: Ubuntu - Test Creator App
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run tests
      run: yarn test --watchAll=false
      env:
        CI: true
    
    - name: Build app
      run: yarn build
  
  # macOS job - Build Flutter app for macOS
  macos-build:
    name: macOS - Build Viewer App
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
      working-directory: manga_viewer
    
    - name: Build macOS app (debug)
      run: flutter build macos --debug
      working-directory: manga_viewer
    
    - name: Upload macOS build
      uses: actions/upload-artifact@v4
      with:
        name: manga-viewer-macos
        path: manga_viewer/build/macos/Build/Products/Debug/manga_viewer.app
        retention-days: 7
  
  # Web job - Build Flutter app for web
  web-build:
    name: Web - Build Viewer App
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
      working-directory: manga_viewer
    
    - name: Build web app (release)
      run: flutter build web --release --base-href=/manga-viewer/
      working-directory: manga_viewer
    
    - name: Upload web build
      uses: actions/upload-artifact@v4
      with:
        name: manga-viewer-web
        path: manga_viewer/build/web
        retention-days: 30
    
    # Optional: Deploy to GitHub Pages
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/configure-pages@v4
      
    - name: Upload Pages artifact
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        path: manga_viewer/build/web
  
  # Deploy to GitHub Pages (only on main branch)
  deploy-pages:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: web-build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4